apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
  namespace: platform
data:
  KAFKA_BROKERS: "kafka-headless.platform.svc.cluster.local:9092"
  CLICKHOUSE_URL: "http://clickhouse.platform.svc.cluster.local:8123"
  LOG_LEVEL: "info"
  ENVIRONMENT: "production"
